CREATE TABLE IF NOT EXISTS users (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(50)  NOT NULL,
    password_hash VARCHAR(64) NOT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_users_username UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS categories (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    description TEXT         DEFAULT NULL,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_categories_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS suppliers (
    id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(150) NOT NULL,
    contact_person VARCHAR(100) DEFAULT NULL,
    email          VARCHAR(120) DEFAULT NULL,
    phone          VARCHAR(30)  DEFAULT NULL,
    created_at     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS items (
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku         VARCHAR(50)    NOT NULL,
    name        VARCHAR(150)   NOT NULL,
    category_id INT            REFERENCES categories(id) ON DELETE SET NULL,
    supplier_id INT            REFERENCES suppliers(id)  ON DELETE SET NULL,
    quantity    INT            NOT NULL DEFAULT 0,
    unit_price  NUMERIC(12, 2) NOT NULL DEFAULT 0.00,
    created_at  TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_items_sku UNIQUE (sku)
);

CREATE TABLE IF NOT EXISTS stock_transactions (
    id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id          INT          NOT NULL REFERENCES items(id) ON DELETE CASCADE,
    transaction_type VARCHAR(3)   NOT NULL CHECK (transaction_type IN ('IN', 'OUT')),
    quantity         INT          NOT NULL,
    notes            TEXT         DEFAULT NULL,
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_items_updated_at ON items;
CREATE TRIGGER trg_items_updated_at
    BEFORE UPDATE ON items
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

INSERT INTO users (username, password_hash) VALUES
    ('admin', '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9');

INSERT INTO categories (name, description) VALUES
    ('Electronics',  'Electronic components and devices'),
    ('Office Supply', 'Stationery and office consumables'),
    ('Furniture',    'Desks, chairs, and shelving'),
    ('Raw Material', 'Unprocessed materials for production');

INSERT INTO suppliers (name, contact_person, email, phone) VALUES
    ('TechSource PH',   'Juan dela Cruz',  'juan@techsource.ph',  '09171000001'),
    ('OfficeWorld Inc.','Maria Santos',    'maria@officeworld.ph','09171000002'),
    ('FurnCo Depot',    'Carlos Reyes',    'carlos@furnco.ph',    '09171000003');

INSERT INTO items (sku, name, category_id, supplier_id, quantity, unit_price) VALUES
    ('ELEC-001', 'USB-C Hub 7-Port',       1, 1, 50,  1299.00),
    ('ELEC-002', 'Mechanical Keyboard',    1, 1, 30,  3499.00),
    ('OFSC-001', 'A4 Bond Paper (500s)',   2, 2, 200,  225.00),
    ('OFSC-002', 'Whiteboard Marker Set',  2, 2, 80,   149.00),
    ('FURN-001', 'Ergonomic Office Chair', 3, 3, 10,  8999.00),
    ('FURN-002', 'Standing Desk 140cm',    3, 3, 5,  15500.00),
    ('RAWM-001', 'Plywood Sheet 3/4"',     4, 3, 100,  650.00);
